#!/bin/bash
# Run MapReduce Job on ChessData Task C
rm ChessDataC.jar
hadoop fs -rm -r chessdata/output_c
hadoop fs -rm -r chessdata/intermediate_output

echo "*****Begin Compiling"
hadoop com.sun.tools.javac.Main ChessDataC.java
echo "*****End Compiling"

echo "*****Begin Jar"
jar cf ChessDataC.jar ChessDataC*.class
echo "*****End Jar"

echo "*****Begin MapReduce"
hadoop jar ChessDataC.jar ChessDataC chessdata/input chessdata/output_c
echo "*****End MapReduce"

echo "*****Print output"
hadoop fs -cat chessdata/output_c/*
